[package]
name = "kardashev-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["http2", "tracing", "ws"] }
clap = { version = "4.5.18", features = ["derive", "env"] }
color-eyre = "0.6"
dotenvy = "0.15"
mime = "0.3.17"
notify-async = { git = "https://github.com/FeraeLabs/notify-async.git" }
sqlx = { version = "0.7.4", features = ["postgres", "runtime-tokio"] }
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }
tokio-util = "0.7.12"
tower-http = { version = "0.6.0", features = ["fs"] }
tower-service = "0.3.3"
tracing = "0.1"
tracing-subscriber = "0.3"
