[package]
name = "kardashev-docs"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
dotenvy = "0.15.7"
humantime = "2.1.0"
structopt = "0.3.26"
tabled = "0.15.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
