[package]
name = "kardashev-client"
version = "0.1.0"
edition = "2021"

[dependencies.kardashev-protocol]
workspace = true

[dependencies]
reqwest = { version = "0.12.7", features = ["json"] }
reqwest-websocket = "0.4.2"
thiserror = "1.0.64"
url = "2.5.2"
